#!/bin/bash
set -o nounset
set -o errexit
# Configuryd for Ubuntu bionic 18.04


srcLib="https://raw.githubusercontent.com/Xakki/kvm.scripts/master/src/bashlibs.sh"
if [[ -f "bashlibs.sh" ]]; then
    echo "Lib bashlibs.sh exist [OK]"
else
    wget -nv --cache=off "$srcLib"
    chmod 0744 bashlibs.sh
fi
. bashlibs.sh

if [[ -z $BLV ]]; then
    echo "Ошибка загрузки библеотеки [error]"
    exit 0
else
    echo "Загруженна библеотека с версией $BLV [OK]"
fi

apt-get -qq install lsb-release
codeName="$(lsb_release -c -s)"
srcMaster="https://github.com/Xakki/Linux-Install-Manual/raw/master"

echo 
echo "****** Start ******" 
echo

############## NGINX
wget http://nginx.org/keys/nginx_signing.key -O nginx_signing.key
apt-key add nginx_signing.key
listName="/etc/apt/sources.list.d/nginx.list"
echo "" > "$listName"
echo "deb [arch=amd64] http://nginx.org/packages/ubuntu/ bionic nginx" >> "$listName"
#echo "deb-src [arch=amd64] http://nginx.org/packages/ubuntu/ bionic nginx" >> "$listName"

############# PHP
add-apt-repository ppa:ondrej/php

############# Mysql-MariaDB
# Установка пакета управления репозиториями
apt install software-properties-common -y
# Импорт и добавление ключа
apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
# Добавление репозитория в apt
add-apt-repository 'deb [arch=amd64] http://mirror.mephi.ru/mariadb/repo/10.3/ubuntu bionic main'

#Postgres
echo "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt/ $codeName-pgdg main" > "/etc/apt/sources.list.d/pgdg.list"
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

echo " ******* Remove apache ******"
apt purge apache2*

echo
myAskYN "APT configured! Continue?" || exit 0
echo

apt update
apt install -y software-properties-common python-software-properties nginx memcached git tor
apt install -y mariadb-server mariadb-client
# переутановка БД - удалить /var/lib/mysql
# mysql_install_db --user=mysql
# mysql_secure_installation # обнуление базы
apt install -y sphinxsearch
apt install postgresql-10

#if myAskYN "Install php5.6 ?"; then
############# for PHP 5
apt install -y php5.6-fpm php5.6-cli php5.6-bcmath php5.6-curl php5.6-gd php5.6-imap php5.6-json php5.6-mbstring php5.6-mcrypt php5.6-mysql php5.6-opcache php5.6-xml php5.6-xsl php5.6-zip
## ioncube plugin
wget $srcMaster/src/ioncube_loader_lin_5.6.so -O /usr/lib/php/20131226/ioncube_loader_lin_5.6.so
echo "zend_extension=ioncube_loader_lin_5.6.so" > /etc/php/5.6/mods-available/ioncube.ini
ln -sf /etc/php/5.6/mods-available/ioncube.ini /etc/php/5.6/fpm/conf.d/04-ioncube.ini
ln -sf /etc/php/5.6/mods-available/ioncube.ini /etc/php/5.6/cli/conf.d/04-ioncube.ini
sed -i.bak "s/short_open_tag = Off/short_open_tag = On/g" /etc/php/5.6/fpm/php.ini
sed -i.bak "s/short_open_tag = Off/short_open_tag = On/g" /etc/php/5.6/cli/php.ini
service php5.6-fpm stop
#fi

#myAskYN "Continue?" || exit 0

############# for PHP 7
apt -y install php7.2 php7.2-bcmath php7.2-cgi php7.2-cli php7.2-common php7.2-curl php7.2-fpm php7.2-gd php7.2-imap php7.2-json php7.2-mbstring php7.2-mysql php7.2-opcache php7.2-zip php7.2-gmp
sed -i.bak "s/short_open_tag = Off/short_open_tag = On/g" /etc/php/7.2/fpm/php.ini
sed -i.bak "s/short_open_tag = Off/short_open_tag = On/g" /etc/php/7.2/cli/php.ini


############# NGINX configure
mkdir /etc/nginx/ssl
openssl dhparam -out /etc/nginx/ssl/dh2048.pem 2048
# openssl dhparam -out /etc/nginx/ssl/dh4096.pem 4096

wget $srcMaster/src/nginx/fpm5.6 -O /etc/nginx/fpm5.6
wget $srcMaster/src/nginx/fpm7.2 -O /etc/nginx/fpm7.2
wget $srcMaster/src/nginx/proxy_params -O /etc/nginx/proxy_params
wget $srcMaster/src/nginx/static_params -O /etc/nginx/static_params
chown -R root:root /etc/nginx/
find /etc/nginx/ -type f -exec chmod 0664 {} \;
# find . -type d -exec chmod 0775 {} \;
# chenge nginx.conf user to www-data

service php7.2-fpm stop
service nginx stop
service sphinxsearch stop
service memcached stop
service mysql stop
service mysql stop
service postgresql stop

apt upgrade -y

if myAskYN "Set link? Attention! Old files will be removed! "; then

rm -R /etc/sphinxsearch
ln -sf /home/wephost/etc/sphinxsearch /etc/sphinxsearch

rm -R /var/lib/mysql
ln -sf /media/DATA/www/DB/mysql /var/lib/mysql

rm -R /var/lib/sphinxsearch
ln -sf /media/DATA/www/DB/sphinxsearch /var/lib/sphinxsearch

cp /home/wephost/etc/nginx/sites-enabled/wephost.conf /etc/nginx/conf.d/

fi

echo "ControlPort 9051" >> /etc/tor/torrc
service tor stop

apt install net-tools virt-manager ssh autossh htop composer
ssh-add ~/.ssh/id_rsa # set default key
