#!/bin/bash

apt-get -qq install lsb-release
codeName="$(lsb_release -c -s)"

wget http://nginx.org/keys/nginx_signing.key -O nginx_signing.key
apt-key add nginx_signing.key
listName="/etc/apt/sources.list.d/nginx.list"
echo "" > "$listName"
echo "deb http://nginx.org/packages/ubuntu/ $codeName nginx" >> "$listName"
echo "deb-src http://nginx.org/packages/ubuntu/ $codeName nginx" >> "$listName"
echo "Nginx ready for instal - OK"

add-apt-repository ppa:ondrej/php
apt-get update
apt-get install -y software-properties-common python-software-properties
apt -y install nginx memcached git


############# Mysql-MariaDB
# Установка пакета управления репозиториями
apt-get install software-properties-common -y
# Импорт и добавление ключа
apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
# Добавление репозитория в apt
add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://mirror.mephi.ru/mariadb/repo/10.1/ubuntu xenial main'
apt -y install mariadb-server mariadb-client
# переутановка БД - удалить /var/lib/mysql
# mysql_install_db --user=mysql
mysql_secure_installation


############# for PHP 5
#apt install php5.6-bcmath php5.6-curl php5.6-gd php5.6-imap php5.6-json php5.6-mbstring php5.6-mcrypt php5.6-mysql php5.6-opcache php5.6-xml php5.6-xsl php5.6-zip
## ioncube plugin
#wget https://github.com/Xakki/kvm.scripts/raw/master/src/ioncube_loader_lin_5.6.so -O /usr/lib/php/20131226/ioncube_loader_lin_5.6.so
#echo "zend_extension=ioncube_loader_lin_5.6.so" > /etc/php/5.6/mods-available/ioncube.ini
#ln -sf /etc/php/5.6/mods-available/ioncube.ini /etc/php/5.6/fpm/conf.d/04-ioncube.ini
#ln -sf /etc/php/5.6/mods-available/ioncube.ini /etc/php/5.6/cli/conf.d/04-ioncube.ini
#sed -i.bak "s/short_open_tag = Off/short_open_tag = On/g" /etc/php/5.6/fpm/php.ini
#sed -i.bak "s/short_open_tag = Off/short_open_tag = On/g" /etc/php/5.6/cli/php.ini
# service php5.6-fpm restart

############# for PHP 7
apt -y install php7.2 php7.2-bcmath php7.2-cgi php7.2-cli php7.2-common php7.2-curl php7.2-fpm php7.2-gd php7.2-imap php7.2-json php7.2-mbstring php7.2-mysql php7.2-opcache php7.2-zip
sed -i.bak "s/short_open_tag = Off/short_open_tag = On/g" /etc/php/7.2/fpm/php.ini
sed -i.bak "s/short_open_tag = Off/short_open_tag = On/g" /etc/php/7.2/cli/php.ini
service php7.2-fpm restart

############## Апач нафиг
apt purge apache2*

############# NGINX configure
mkdir /etc/nginx/ssl
openssl dhparam -out /etc/nginx/ssl/dh2048.pem 2048
# openssl dhparam -out /etc/nginx/ssl/dh4096.pem 4096

wget https://github.com/Xakki/kvm.scripts/raw/master/src/nginx/fpm5.6 -O /etc/nginx/fpm5.6
wget https://github.com/Xakki/kvm.scripts/raw/master/src/nginx/fpm7.2 -O /etc/nginx/fpm7.2
wget https://github.com/Xakki/kvm.scripts/raw/master/src/nginx/proxy_params -O /etc/nginx/proxy_params
wget https://github.com/Xakki/kvm.scripts/raw/master/src/nginx/static_params -O /etc/nginx/static_params
chown -R root:root /etc/nginx/
# find . -type f -exec chmod 0664 {} \;
# find . -type d -exec chmod 0775 {} \;
# chenge nginx.conf user to www-data
service nginx restart

## Sphinx 2.2 install
# apt install unixodbc libpq5
add-apt-repository ppa:builds/sphinxsearch-rel22
apt update
apt install sphinxsearch
# set config
service sphinxsearch start




